<a href="https://colab.research.google.com/github/Geuens/curso_ai/blob/main/numPy_recetas_ejemplos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---


## Ver la versión de numPy

In [ ]:
import numpy as np

np.__version__

'1.23.5'



---


## Crear un array numpy 10 elementos

In [ ]:
mi_array = np.arange(10)
mi_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



---


## Crear una array con 10 elementos a partir del 100

In [ ]:
np.arange(100,110)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])



---


## Crear una array de ceros de tamaño 5x5

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])



---


## Crear un array de n elementos a partir de un numero

In [ ]:
np.full(10, 20)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])



---


## Crear un array de identidad de 3x3

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



---


## Generar un Array de 20 Puntos entre 0 y 1

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])



---
## Sumar todos los elementos de un Array


In [ ]:
array = np.array([10,10,10,10,10,10,10])
np.sum(array)

70



---

## Restar un valor de todos los Elementos de un array

In [ ]:
array = np.arange(10)
np.subtract(array, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])



---

## Usando reduce vs sum

In [ ]:
array = np.arange(100)
str(np.add.reduce(array)) + ' vs ' + str(np.sum(array))

'4950 vs 4950'



---

## Agrupar los elementos de un array de 3 en tres

In [ ]:
array = np.array([34,5,2,6,5,7,45,3,6,7,454,5])
array = np.reshape(array, (3, (len(array)//3))) # usamos // para que el resultado sea entero y no float
print(array)

[[ 34   5   2   6]
 [  5   7  45   3]
 [  6   7 454   5]]




---

## Transponer un array

In [ ]:
array = np.array([34,5,2,6,5,7,45,3,6,7,454,5])
array = np.reshape(array, (3, (len(array)//3))) # usamos // para que el resultaod sea entero y no float
# pasado de 3 grupos de 4 a 4 grupos de 3
array = np.transpose(array)
print(array)

[[ 34   5   6]
 [  5   7   7]
 [  2  45 454]
 [  6   3   5]]




---
## Aplanar un array


In [ ]:
array = np.array([34,5,2,6,5,7,45,3,6,7,454,5])
array = np.reshape(array, (3, (len(array)//3))) # usamos // para que el resultaod sea entero y no float
array.flatten()

array([ 34,   5,   2,   6,   5,   7,  45,   3,   6,   7, 454,   5])



---
## Reduce con una función personalizada


In [ ]:
array = np.array([34,5,2,6,5,7,45,3,6,7,454,5])

def operacion(x):
  return np.log(x) - np.sqrt(x)
operacion_vectorizada = np.vectorize(operacion)

array = operacion_vectorizada(array)


array([ -2.30459137,  -0.62663007,  -0.72106638,  -0.65773027,
        -0.62663007,  -0.69984116,  -2.90154144,  -0.63343852,
        -0.65773027,  -0.69984116, -15.18917855,  -0.62663007])



---

## Concatenar arrays (Añadir un elemento)


In [ ]:
a = np.array([1, 2, 3])
np.concatenate([a, [4]])

array([1, 2, 3, 4])



---

## Concatenar arrays (Multidimensionales)

In [ ]:
a = np.arange(4).reshape(2, 2)
print(a)
b = np.arange(10, 14).reshape(2, 2)
print(b)
np.concatenate([a, b], axis=1)

[[0 1]
 [2 3]]
[[10 11]
 [12 13]]


array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])